Sistemare il checker

diff --git a/Common_Core_2024/Milestone_2/push_swap/Makefile b/Common_Core_2024/Milestone_2/push_swap/Makefile
--- a/Common_Core_2024/Milestone_2/push_swap/Makefile
+++ b/Common_Core_2024/Milestone_2/push_swap/Makefile
@@ -5,35 +5,35 @@
 #                                                     +:+ +:+         +:+      #
 #    By: igilani <igilani@student.42firenze.it>     +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
-#    Created: 2025/03/03 14:46:42 by igilani           #+#    #+#              #
-#    Updated: 2025/03/26 18:45:47 by igilani          ###   ########.fr        #
+#    Created: 2025/03/28 18:20:10 by igilani           #+#    #+#              #
+#    Updated: 2025/03/28 18:20:59 by igilani          ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
-# Comportamento predefinito
-.DEFAULT_GOAL := silent
-
 # Configurazioni principali
-CC	  	= cc
-CFLAGS  = -Wall -Wextra -Werror -g -O3 -Wno-unused-result
-NAME	= push_swap
-SRC	 	= error_handle.c main.c push_command.c push_swap_command.c push_swap_init.c reverse_rotate_command.c rotate_command.c stack_init.c stack_utils.c swap_command.c tiny_sort.c idx.c rotate_both.c
-HEADERS = push_swap.h
-OBJ_DIR = obj
-OBJ	 	= $(addprefix $(OBJ_DIR)/, $(SRC:.c=.o))
-LIB_DIR = tha_supreme_lib
-BUILD 	= 0
+CC			= cc
+CFLAGS		= -Wall -Wextra -Werror -g -O3 -Wno-unused-result
+NAME		= push_swap
+BONUS		= checker
+SRC			= error_handle.c main.c push_command.c push_swap_command.c push_swap_init.c reverse_rotate_command.c rotate_command.c stack_init.c stack_utils.c swap_command.c tiny_sort.c idx.c rotate_both.c
+SRC_BONUS	= bonus/checker_bonus.c error_handle.c push_command.c push_swap_command.c push_swap_init.c reverse_rotate_command.c rotate_command.c stack_init.c stack_utils.c swap_command.c tiny_sort.c idx.c rotate_both.c
+HEADERS		= push_swap.h
+OBJ_DIR		= obj
+OBJ			= $(addprefix $(OBJ_DIR)/, $(SRC:.c=.o))
+OBJ_BONUS	= $(addprefix $(OBJ_DIR)/, $(notdir $(SRC_BONUS:.c=.o)))
+LIB_DIR		= tha_supreme_lib
+BUILD		= 0
 
 # Librerie
 THA_LIB = $(LIB_DIR)/tha_supreme_lib.a
 
 # Colori ANSI
-RED	 = \033[31m
-ERROR = $(RED)✗
-GREEN   = \033[32m
-YELLOW  = \033[33m
+RED		= \033[31m
+ERROR	= $(RED)✗
+GREEN	= \033[32m
+YELLOW	= \033[33m
 BLUE	= \033[34m
-RESET   = \033[0m
+RESET	= \033[0m
 
 all: $(NAME)
 	@if [ $(BUILD) -eq 1 ]; then \
@@ -41,6 +41,15 @@ all: $(NAME)
 	else \
 		if [ $(BUILD) -eq 0 ]; then \
 			echo "$(GREEN)✔ Già tutto compilato$(RESET)"; \
+		fi \
+	fi
+
+bonus: $(BONUS)
+	@if [ $(BUILD) -eq 1 ]; then \
+		echo "$(GREEN)✔ Build completato per bonus$(RESET)"; \
+	else \
+		if [ $(BUILD) -eq 0 ]; then \
+			echo "$(GREEN)✔ Già tutto compilato per bonus$(RESET)"; \
 		fi \
 	fi
 
@@ -58,6 +67,12 @@ $(OBJ_DIR)/%.o: %.c $(HEADERS) | $(OBJ_DIR)
 		exit 1; \
 	}
 
+$(OBJ_DIR)/%.o: bonus/%.c $(HEADERS) | $(OBJ_DIR)
+	@$(CC) $(CFLAGS) -c $< -o $@ || { \
+		echo "$(ERROR) Errore nella compilazione di $<$(RESET)"; \
+		exit 1; \
+	}
+
 $(OBJ_DIR):
 	@mkdir -p $(OBJ_DIR)
 
@@ -70,6 +85,15 @@ $(NAME): $(OBJ) $(THA_LIB)
 	@echo "$(BLUE)➜ Creazione eseguibile $(NAME)...$(RESET)"
 	@echo "$(GREEN)✔ Eseguibile $(NAME) generato$(RESET)"
 
+$(BONUS): $(OBJ_BONUS) $(THA_LIB)
+	@$(CC) $(CFLAGS) $(OBJ_BONUS) -o $(BONUS) $(THA_LIB) || { \
+		echo "$(ERROR) Errore durante il linking finale per bonus$(RESET)"; \
+		exit 1; \
+	}
+	@$(eval BUILD = 1)
+	@echo "$(BLUE)➜ Creazione eseguibile $(BONUS)...$(RESET)"
+	@echo "$(GREEN)✔ Eseguibile $(BONUS) generato$(RESET)"
+
 clean:
 	@$(MAKE) -s -C $(LIB_DIR) clean > /dev/null 2>&1
 	@echo "$(BLUE)➜ File oggetto da $(YELLOW)$(LIB_DIR)$(RESET) $(BLUE)rimossi$(RESET)"
@@ -78,12 +102,12 @@ clean:
 
 fclean: clean
 	@$(MAKE) -s -C $(LIB_DIR) fclean > /dev/null 2>&1
-	@rm -f $(NAME)
-	@echo "$(BLUE)➜ Eseguibile $(YELLOW)$(NAME)$(RESET) $(BLUE)rimosso$(RESET)"
+	@rm -f $(NAME) $(BONUS)
+	@echo "$(BLUE)➜ Eseguibili $(YELLOW)$(NAME) e $(BONUS)$(RESET) $(BLUE)rimossi$(RESET)"
 
 re: fclean all
 
 silent:
 	@$(MAKE) all 2>&1 | grep -v '^make\[.*\]:'
 
-.PHONY: all clean fclean re lib_check silent
+.PHONY: all clean fclean re bonus silent
